# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
   install:
      - method: pip
        path: .
        extra_requirements:
            - cli
            - docs

formats: all

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
